version: '3'
services:
  webserver:
    image: surajbele/students:v2
    ports:
      - 8080:8080
  appserver:
    image: httpd
    ports:
      - 80:80
  dbserver:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin123