apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: myapp
    env: Devops
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: httpd
          containerPort: 80
