apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    name: my-svc
    env: Devops
spec:
  type: ClusterIP
  selector:
    name: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

    